---
picture:  pics/resume.jpeg
name: "Christian Tillich"
occupation: "Data Science"
address: "Chicago, Il."
phone: "847-863-7162"
website: "github/christiantillich"
email: "christian.tillich.walker@gmail.com"
statistics:
  - {name: "`General Stats & Opt`", score: 4}
  - {name: "`Bayesian Statistics`", score: 2}
  - {name: "`Multivariate Methods`", score: 3}
  - {name: "`Clustering`", score: 4}
  - {name: "`Tree Methods - RF & XGB`", score: 5}
  - {name: "`Regression`", score: 6}
programming:
  - {name: "`AWS / Other Cloud`", score: 3}
  - {name: "`Git`", score: 3}
  - {name: "`Documentation Tools`", score: 4}
  - {name: "`SQL`", score: 5}
  - {name: "`Python`", score: 4}
  - {name: "`R`", score: 5}
  
output: 
  pdf_document:
    # keep_tex: TRUE
    template: latex/template.tex
geometry: 
 - left = 6.7cm
 - top = 0.5cm 
 - right = 1cm
 - bottom = 0.2cm 
 - nohead 
 - nofoot
---

# Work Experience

## Numerator \hfill Data Science: Panel Science \hfill May 2020 - Present

* Designed and released new version of Allocation model. 
    * Developed and maintained a library of known failures of the previous
    methods, with detailed causal analysis of failure modes.
    * Updated the distribution assumptions and calculation to align with industry best practices. 
    * Developed production pipeline for model fitting, and orchestrated in Airflow.
    * Responded rapidly to feedback during UAT, iterating through numerous design considerations and edge cases to final implementation. 
* Designed experimental Brand Strength model, connecting survey responses to actual market behaviors for participating panelists. 
* Developed numerous internal tools to assist with day-to-day DS functions
    * Python wrapper for Insights API
    * Lightweight model development framework for rapid local experimentation. 
    * Other DS tooling to improve Snowflake workflows. 

## Uptake \hfill Data Science: Assessments \hfill Mar 2019 - April 2020

* Constructed machine learning models to assist manufacturing clients in diagnosing and troubleshooting common failures on assets. 
    * Anomaly detection models to capture errant behavior on stamping presses. 
    * Rare-event prediction models to detect chock bearing and spindle failures for well-known steel manufacturer. 
    * Unsupervised classification to clean operator labels in work-order data.
* Converted client engagements in the Mining and Manufacturing space. 
* Assisted in efforts to evaluate new technologies relevant to Data Science work. 

## Avant Credit \hfill Data Science \hfill Jun 2016 - Mar 2019

* Constructed machine learning models for the portfolio, including:
    * Core underwriting model for prime population. 
    * Competitor underwriting models using alternative consumer credit sources
    * Unsupervised segmentation model for targeted marketing.
    * Modeling suite to enhance refinance target logic.
* Monitored models performance for degradation, suggested remedies and rebuilds.
* Built, documented, and maintained a shared automated reporting toolset for the team. 
* Built, documented, and maintained a tool for managing data preprocessing.
* Contributed to a repository of shared functions and tests.
* Trained and informally managed new team members

\newpage \makeprofile

## Avant Credit \hfill Business Analytics \hfill Sep 2015 - June 2016

* Designed critical long-term risk forecasting tool.
    * Linear regression to turn unintuitive underwriting score into sensible 12-month risk metric 
    * Custom curve-fitting optimization to map 12-month risk to marginal risk curve over life of loan.
    * Tool accurately forecast losses during a period of high risk and low access to capital.
* Performed investigative data analysis on several topics.
    * Optimal way to quantify debt to income. 
    * Reverse engineering competitive products from credit report tradelines. 

## Enova Financial \hfill Research & Platforms \hfill Dec 2014 - Sep 2015

* Researched the efficacy of non-linear modeling strategies. 
* Developed unsupervised learning model to tag call center notes on a variety of topics.
* Designed and maintained core analytics Data Mart. 
* Evaluated the efficacy of voice-to-text translation software for call center.

## Enova Financial \hfill UK Business Analytics \hfill Jan 2014 - Dec 2015

* Designed profit-maximizing loan amount optimization tool. Raised average loan amounts by $60 and expected net return by 7%. 
* Led all analytics efforts in major legal overhaul. Salvaged $5 million in above worst-case scenarios. 

## Enova Financial \hfill CA/AU Business Analytics \hfill Aug 2010 - Jan 2014

* Identified and fixed key failures of underwriting engine. 
* Created LTV calculator used to optimize digital marketing allocations. 
* Informally managed team of 2-5 analysts working on different aspects of the underwriting engine. 
* Identified and shut down *ad hoc* fraud pockets on the two products. 

## Enova Financial \hfill Fraud/Operations Analyst \hfill Jun 2008 - Aug 2010

* Developed critical reports that allowed us to open operations after massive fraud attack. 
* Wrote and implemented a number of consistency checks to catch operational and development errors and report back to stakeholders. 

\newpage \makeprofile

# Academic Research

## Research Assistant \hfill Granato Research Team \hfill Sep 2006 - Sep 2007

* Prepared samples for experiments. 
* Prepared preliminary findings for NSF grant proposals.

## Research Assistant \hfill CERI Research Team \hfill May 2006 - Aug 2006

* Wrote Matlab scripts to determine theoretical surface depth from excessive loading. 
* Wrote Unix shell-scripting to ETL raw GPS data into usable Matlab objects. 
* Presented research to peers at 2 day conference in Oregon. 

# Education

## DePaul University \hfill 2012 - 2015
MS Statistics \hfill GPA: 3.9/4.0

## University of Illinois - UC \hfill 2004 - 2008
BS Physics, Minor in Philosophy \hfill GPA: 3.6/4.0